### ISSUE TITLE
ganache-core is not in the package file and ERC20_TOKEN_CONTRACT_DOES_NOT_EXIST error

### ISSUE THREAD

**Issue by markguo40** [RadarRelay/sdk-bot-example#6]
I am trying to download the package and run. It shows me error that ganache-core not found, so I install ganache-core and the problem resolved.

However, when I run the program, during the boosting:

```
Radar Relay Bot Powering Up 📡
............................🚀ERC20_TOKEN_CONTRACT_DOES_NOT_EXIST
```

It throw me ERC20_TOKEN_CONTRACT_DOES_NOT_EXIST error.

**Comment by smithki** [comment]
Sorry for the inconvenience here. The problem was a typo in our endpoints (we should have been pointing to kovan) 😅. A fix has landed in #7. Thanks for opening an issue.
